// <auto-generated />
namespace GoFinance_API_Sharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class novamodelagem5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(novamodelagem5));
        
        string IMigrationMetadata.Id
        {
            get { return "201802070227497_novamodelagem5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
